% Calculate_F Calculate WOTF for illumination
%
% Inputs:
%   rhoxy           - Spatial frequency coordinates in XY plane [1/μm]
%   eta             - Spatial frequency coordinates in Z direction [1/μm]
%   lambda          - Wavelength of light [μm]
%   rho             - 3D spatial frequency coordinates [1/μm]
%   rhos            - Normalized spatial frequency for current radius [1/μm]
%   rhop            - Maximum spatial frequency [1/μm]
%
% Output:
%   Fp              - 3D Weak Object Transfer Function

function Fp = CalculateF(rhoxy,eta,lambda,rho,rhos,rhop)
eta (eta == 0) = eps;
delta1 = eta./rhoxy.*(eta/2 -  sqrt(lambda.^(-2) - rhos.^2));
delta2 = delta1;
delta3 = eta./rhoxy.*(-eta/2 -  sqrt(lambda.^(-2) - rhop.^2));
delta = zeros(size(delta1));

    delta(rhoxy<=(rhop-rhos)... 
        & rhoxy>= 0 ...
        & (       sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - (rhos - rhoxy).^2) <= eta)...
        & (eta <= sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - (rhos + rhoxy).^2)))...
= delta1(rhoxy<=(rhop-rhos)...
        & rhoxy>= 0 ...
        & (       sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - (rhos - rhoxy).^2) <= eta)... 
        & (eta <= sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - (rhos + rhoxy).^2)));

    delta((rhoxy>=(rhop-rhos) & rhoxy<=(rhop+rhos)) ...
        & (        sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - (rhos - rhoxy).^2) <= eta) ...
        & (eta <= (sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - rhop.^2))))...
= delta2((rhoxy>=(rhop-rhos) & rhoxy<=(rhop+rhos)) ...
        & (        sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - (rhos - rhoxy).^2) <= eta) ...
        & (eta <= (sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - rhop.^2))));

   delta((rhoxy>=(rhop-rhos) & rhoxy<=(rhop+rhos)) ...
       & (        sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - rhop.^2) < eta) ...
       & (eta <= (sqrt(lambda.^(-2) - (rhop - rhoxy).^2)) - sqrt(lambda.^(-2) - rhop.^2))) ...
= delta3((rhoxy>=(rhop-rhos) & rhoxy<=(rhop+rhos)) ...
       & (        sqrt(lambda.^(-2) - rhos.^2) - sqrt(lambda.^(-2) - rhop.^2) < eta)...  
       & (eta <= (sqrt(lambda.^(-2) - (rhop - rhoxy).^2)) - sqrt(lambda.^(-2) - rhop.^2)));

Fp = abs(rhoxy.^2.*delta./(rho.^2.*eta))...
.*(sqrt(lambda.^(-2) - rho.^2./4 - rho.^2.*delta.^2./eta.^2)) +...
    (lambda.^(-2) - rho.^2./4 - eta.^2./(2*rho)).*(acos(abs(rho.*delta./(eta)./sqrt(lambda.^(-2) - rho.^2./4))));
Fp(delta == 0)=0;
end




