% RLDTV_WBARL Perform R-L deconvolution with TV regularization and
% Wiener-Butterworth accelerated back-projector.
%
% This function keeps the original RLDTV forward model and TV term, but
% replaces the traditional flipped PSF back-projector with the mismatched
% Wiener-Butterworth back-projector generated by WB_back_projector.m.
%
% Inputs:
%   raw                 - 2D captured raw HSEDOF data (blurred)
%   PSF_fp              - 2D forward PSF kernel or image-sized PSF
%   niter               - number of iterations
%   nonnegBeta          - non-negativity lower bound used in RLD update
%   TV                  - TV regularization parameter
%   wbParam             - struct for WB back-projector parameters:
%                         .bp_type     default 'wiener-butterworth'
%                         .alpha       default 0.001
%                         .beta        default 0.001  % WB cutoff gain, not nonnegBeta
%                         .n           default 10
%                         .resFlag     default 1
%                         .iRes        default [0 0 0]
%                         .verboseFlag default 0
%                         .epsValue    default 1e-12
%                         .PSF_bp      optional precomputed back-projector
%   showProgress (opt.) - logical, whether to print iteration progress
%   label        (opt.) - char/string, label for progress, e.g. 'R','G','B'
%
% Outputs:
%   ImageEstimate       - 2D deconvolution result
%   PSF_bp              - WB mismatched back-projector used in the iteration

function [ImageEstimate, PSF_bp] = RLDTV_WBARL(raw, PSF_fp, niter, nonnegBeta, TV, wbParam, showProgress, label)

    % -------- handle optional arguments --------
    if nargin < 6 || isempty(wbParam)
        wbParam = struct();
    end
    if nargin < 7 || isempty(showProgress)
        showProgress = false;
    end
    if nargin < 8
        label = '';
    end

    if ~isa(raw, 'gpuArray')
        raw = double(raw);
    end
    PSF_fp = cast(PSF_fp, 'like', raw);

    % RLDTV in this project is a 2D deconvolution function.  If a singleton
    % third dimension is present, remove it; otherwise require exact size match.
    if ndims(PSF_fp) == 3 && size(PSF_fp, 3) == 1
        PSF_fp = PSF_fp(:, :, 1);
    end
    if ~ismatrix(raw) || ~ismatrix(PSF_fp)
        error('RLDTV_WBARL expects 2D raw data and a 2D forward PSF.');
    end

    % Normalize the forward PSF if possible.  This keeps the forward projector
    % scale stable when PSFs are loaded from external files.
    psfSum = sum(PSF_fp(:));
    psfSumCheck = psfSum;
    if isa(psfSum, 'gpuArray')
        psfSumCheck = gather(psfSum);
    end
    if isfinite(psfSumCheck) && abs(psfSumCheck) > 0
        PSF_fp = PSF_fp ./ psfSum;
    end

    % -------- generate or read the mismatched WB back-projector --------
    if isfield(wbParam, 'PSF_bp') && ~isempty(wbParam.PSF_bp)
        PSF_bp = cast(wbParam.PSF_bp, 'like', raw);
    else
        bp_type     = getOption(wbParam, 'bp_type', 'wiener-butterworth');
        wbAlpha     = getOption(wbParam, 'alpha', 0.001);
        wbBeta      = getOption(wbParam, 'beta', 0.001);
        wbOrder     = getOption(wbParam, 'n', 10);
        resFlag     = getOption(wbParam, 'resFlag', 1);
        iRes        = getOption(wbParam, 'iRes', [0, 0, 0]);
        verboseFlag = getOption(wbParam, 'verboseFlag', 0);

        iRes = iRes(:).';
        if numel(iRes) == 2
            iRes = [iRes, 1];
        elseif numel(iRes) < 2
            iRes = [0, 0, 0];
        elseif numel(iRes) > 3
            iRes = iRes(1:3);
        end

        [PSF_bp, ~] = WB_back_projector(PSF_fp, bp_type, wbAlpha, wbBeta, wbOrder, resFlag, iRes, verboseFlag);
    end

    if ndims(PSF_bp) == 3 && size(PSF_bp, 3) == 1
        PSF_bp = PSF_bp(:, :, 1);
    end
    PSF_bp = cast(PSF_bp, 'like', raw);

    epsValue = cast(getOption(wbParam, 'epsValue', 1e-12), 'like', raw);

    % Preserve the original RLD code's intensity inversion convention.
    raw = max(raw(:)) - raw;
    ImageEstimate = raw;
    [Ny, Nx] = size(raw);

    % FFTs of projectors do not change during iterations, so compute once.
    Hpsf = psfToOTF2D(PSF_fp, [Ny, Nx]);
    Hbp  = psfToOTF2D(PSF_bp, [Ny, Nx]);

    if showProgress
        tStart = tic;
    end

    for iter = 1:niter
        % ===== Forward projection =====
        HI = fftshift(fftn(ImageEstimate));
        Conv = real(ifftn(ifftshift(Hpsf .* HI)));
        Conv = max(Conv, epsValue);

        % ===== RL ratio and WB mismatched back-projection =====
        DV = raw ./ Conv;
        DV(~isfinite(DV)) = 0;

        HDV = fftshift(fftn(DV));
        DV_Conv = real(ifftn(ifftshift(HDV .* Hbp)));

        % ===== TV regularization term: same form as original RLDTV =====
        p = zeros(Ny, Nx, 2, 'like', ImageEstimate);
        p(:, :, 1) = ImageEstimate(:, [2:Nx, Nx]) - ImageEstimate;
        p(:, :, 2) = ImageEstimate([2:Ny, Ny], :) - ImageEstimate;

        p = 16 * p;
        normep = max(ones(1, 'like', ImageEstimate), sqrt(p(:, :, 1).^2 + p(:, :, 2).^2));
        p(:, :, 1) = p(:, :, 1) ./ normep;
        p(:, :, 2) = p(:, :, 2) ./ normep;

        zeroRow = zeros(1, Nx, 'like', ImageEstimate);
        zeroCol = zeros(Ny, 1, 'like', ImageEstimate);
        div = [p(1:Ny-1, :, 2); zeroRow] - [zeroRow; p(1:Ny-1, :, 2)];
        div = [p(:, 1:Nx-1, 1), zeroCol] - [zeroCol, p(:, 1:Nx-1, 1)] + div;

        denom = 1 - TV .* div;
        denom = max(denom, epsValue);

        ImageEstimate = DV_Conv .* ImageEstimate ./ denom;
        ImageEstimate = real(ImageEstimate);
        ImageEstimate(~isfinite(ImageEstimate)) = nonnegBeta;
        ImageEstimate = max(ImageEstimate, nonnegBeta);

        % ===== command-line progress =====
        if showProgress
            if isa(ImageEstimate, 'gpuArray')
                wait(gpuDevice);
            end
            elapsed = toc(tStart);
            eta = elapsed / iter * (niter - iter);
            if isempty(label)
                fprintf('\rRLDTV-WBARL iter %d/%d | Elapsed %.1fs | ETA %.1fs', ...
                        iter, niter, elapsed, eta);
            else
                fprintf('\r[%s] RLDTV-WBARL iter %d/%d | Elapsed %.1fs | ETA %.1fs', ...
                        label, iter, niter, elapsed, eta);
            end
        end
    end

    if showProgress
        fprintf('\n');
    end

    % Convert back to the same polarity convention as the input image.
    ImageEstimate = max(ImageEstimate(:)) - ImageEstimate;
    ImageEstimate = real(ImageEstimate);
    ImageEstimate(~isfinite(ImageEstimate)) = 0;
    ImageEstimate = max(ImageEstimate, 0);

end

function value = getOption(s, fieldName, defaultValue)
    if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
        value = s.(fieldName);
    else
        value = defaultValue;
    end
end
